name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test
        run: chmod +x test.sh && ./test.sh
